-- ============================================================
-- V9 - PEDIDOS
-- Smart Store
-- ============================================================


-- ============================================================
-- 1. ESTADOS DE PEDIDO
-- ============================================================

CREATE TABLE estados_pedido (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              nombre VARCHAR(50) NOT NULL,
                              descripcion VARCHAR(255),

                              activo BOOLEAN NOT NULL DEFAULT TRUE,

                              fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT uq_estados_pedido_nombre
                                UNIQUE (nombre)
);


-- ============================================================
-- 2. PEDIDOS
--
-- El pedido pertenece a una sede.
-- El cliente pertenece al comercio.
--
-- usuario_id puede ser NULL porque inicialmente los pedidos
-- podrán ser creados automáticamente desde WhatsApp.
--
-- No almacenamos total_pedido porque se obtiene a partir
-- de los detalles.
-- ============================================================

CREATE TABLE pedidos (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                       sede_id BIGINT NOT NULL,
                       cliente_id BIGINT NOT NULL,
                       estado_pedido_id BIGINT NOT NULL,

                       usuario_id BIGINT,

                       observacion VARCHAR(500),

                       fecha_pedido TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       fecha_confirmacion TIMESTAMPTZ,
                       fecha_entrega TIMESTAMPTZ,
                       fecha_cancelacion TIMESTAMPTZ,

                       fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uq_pedidos_uuid_publico
                         UNIQUE (uuid_publico),

                       CONSTRAINT fk_pedidos_sede
                         FOREIGN KEY (sede_id)
                           REFERENCES sedes(id),

                       CONSTRAINT fk_pedidos_cliente
                         FOREIGN KEY (cliente_id)
                           REFERENCES clientes(id),

                       CONSTRAINT fk_pedidos_estado
                         FOREIGN KEY (estado_pedido_id)
                           REFERENCES estados_pedido(id),

                       CONSTRAINT fk_pedidos_usuario
                         FOREIGN KEY (usuario_id)
                           REFERENCES usuarios(id),

                       CONSTRAINT ck_pedidos_fecha_confirmacion
                         CHECK (
                           fecha_confirmacion IS NULL
                             OR fecha_confirmacion >= fecha_pedido
                           ),

                       CONSTRAINT ck_pedidos_fecha_entrega
                         CHECK (
                           fecha_entrega IS NULL
                             OR fecha_entrega >= fecha_pedido
                           ),

                       CONSTRAINT ck_pedidos_fecha_cancelacion
                         CHECK (
                           fecha_cancelacion IS NULL
                             OR fecha_cancelacion >= fecha_pedido
                           )
);


-- ============================================================
-- 3. DETALLES DEL PEDIDO
--
-- precio_unitario representa el precio que tenía el producto
-- en el momento de realizar el pedido.
--
-- Esto es intencional: aunque posteriormente cambie el precio
-- del catálogo, el pedido conserva su precio histórico.
--
-- No almacenamos subtotal.
-- subtotal = cantidad * precio_unitario
-- ============================================================

CREATE TABLE detalles_pedido (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               pedido_id BIGINT NOT NULL,
                               variante_producto_sede_id BIGINT NOT NULL,

                               cantidad NUMERIC(14,3) NOT NULL,
                               precio_unitario NUMERIC(14,2) NOT NULL,

                               fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_detalles_pedido_pedido
                                 FOREIGN KEY (pedido_id)
                                   REFERENCES pedidos(id),

                               CONSTRAINT fk_detalles_pedido_variante_producto_sede
                                 FOREIGN KEY (variante_producto_sede_id)
                                   REFERENCES variantes_producto_sede(id),

                               CONSTRAINT ck_detalles_pedido_cantidad
                                 CHECK (cantidad > 0),

                               CONSTRAINT ck_detalles_pedido_precio_unitario
                                 CHECK (precio_unitario >= 0),

                               CONSTRAINT uq_detalles_pedido_variante
                                 UNIQUE (pedido_id, variante_producto_sede_id)
);


-- ============================================================
-- 4. DIRECCIÓN DE ENTREGA DEL PEDIDO
--
-- Esta tabla es una "fotografía" de la dirección utilizada
-- en el momento del pedido.
--
-- NO depende de direcciones_cliente.
--
-- Si el cliente modifica o elimina posteriormente su dirección,
-- el pedido conserva exactamente dónde debía entregarse.
--
-- Puede no existir para pedidos de recogida en tienda.
-- ============================================================

CREATE TABLE direcciones_entrega_pedido (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                          pedido_id BIGINT NOT NULL,
                                          ciudad_id BIGINT NOT NULL,

                                          direccion VARCHAR(255) NOT NULL,
                                          barrio VARCHAR(100),
                                          referencia VARCHAR(255),

                                          fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                          CONSTRAINT fk_direcciones_entrega_pedido_pedido
                                            FOREIGN KEY (pedido_id)
                                              REFERENCES pedidos(id),

                                          CONSTRAINT fk_direcciones_entrega_pedido_ciudad
                                            FOREIGN KEY (ciudad_id)
                                              REFERENCES ciudades(id),

                                          CONSTRAINT uq_direcciones_entrega_pedido_pedido
                                            UNIQUE (pedido_id),

                                          CONSTRAINT ck_direcciones_entrega_pedido_direccion
                                            CHECK (btrim(direccion) <> '')
);


-- ============================================================
-- 5. RELACIÓN PEDIDO - MOVIMIENTO DE INVENTARIO
--
-- Nos permite conocer qué detalle de pedido originó cada
-- movimiento de inventario.
--
-- Un detalle puede producir varios movimientos:
--
-- RESERVA
-- LIBERACION
-- ENTREGA
--
-- Por eso detalle_pedido_id NO es UNIQUE.
-- ============================================================

CREATE TABLE movimientos_inventario_pedido (
                                             movimiento_inventario_id BIGINT NOT NULL,
                                             detalle_pedido_id BIGINT NOT NULL,

                                             CONSTRAINT pk_movimientos_inventario_pedido
                                               PRIMARY KEY (
                                                            movimiento_inventario_id,
                                                            detalle_pedido_id
                                                 ),

                                             CONSTRAINT fk_movimientos_inventario_pedido_movimiento
                                               FOREIGN KEY (movimiento_inventario_id)
                                                 REFERENCES movimientos_inventario(id),

                                             CONSTRAINT fk_movimientos_inventario_pedido_detalle
                                               FOREIGN KEY (detalle_pedido_id)
                                                 REFERENCES detalles_pedido(id)
);


-- ============================================================
-- 6. ÍNDICES
-- ============================================================

CREATE INDEX idx_pedidos_sede
  ON pedidos(sede_id);

CREATE INDEX idx_pedidos_cliente
  ON pedidos(cliente_id);

CREATE INDEX idx_pedidos_estado
  ON pedidos(estado_pedido_id);

CREATE INDEX idx_pedidos_usuario
  ON pedidos(usuario_id);

CREATE INDEX idx_pedidos_fecha
  ON pedidos(fecha_pedido);

CREATE INDEX idx_detalles_pedido_pedido
  ON detalles_pedido(pedido_id);

CREATE INDEX idx_detalles_pedido_variante_producto_sede
  ON detalles_pedido(variante_producto_sede_id);

CREATE INDEX idx_direcciones_entrega_pedido_ciudad
  ON direcciones_entrega_pedido(ciudad_id);

CREATE INDEX idx_movimientos_inventario_pedido_detalle
  ON movimientos_inventario_pedido(detalle_pedido_id);


-- ============================================================
-- 7. ESTADOS INICIALES
-- ============================================================

INSERT INTO estados_pedido
(nombre, descripcion)
VALUES
  (
    'CREADO',
    'Pedido creado y pendiente de confirmación'
  ),
  (
    'CONFIRMADO',
    'Pedido confirmado para ser procesado'
  ),
  (
    'PREPARANDO',
    'Pedido en proceso de preparación'
  ),
  (
    'LISTO',
    'Pedido preparado y listo para entrega o recogida'
  ),
  (
    'ENTREGADO',
    'Pedido entregado al cliente'
  ),
  (
    'CANCELADO',
    'Pedido cancelado'
  );
