-- ============================================================
-- V11 - PAGOS
-- Smart Store
-- ============================================================


-- ============================================================
-- 1. METODOS DE PAGO
-- ============================================================

CREATE TABLE metodos_pago (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            nombre VARCHAR(50) NOT NULL,
                            descripcion VARCHAR(255),

                            activo BOOLEAN NOT NULL DEFAULT TRUE,

                            fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT uq_metodos_pago_nombre
                              UNIQUE (nombre)
);


-- ============================================================
-- 2. ESTADOS DE PAGO
-- ============================================================

CREATE TABLE estados_pago (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            nombre VARCHAR(50) NOT NULL,
                            descripcion VARCHAR(255),

                            activo BOOLEAN NOT NULL DEFAULT TRUE,

                            fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT uq_estados_pago_nombre
                              UNIQUE (nombre)
);


-- ============================================================
-- 3. PAGOS
--
-- Un pedido puede tener múltiples pagos.
--
-- Ejemplo:
-- Pedido $50.000
--
-- Efectivo       $20.000
-- Transferencia  $30.000
--
-- usuario_verificador_id puede ser NULL porque un pago puede
-- estar pendiente o ser confirmado automáticamente en el futuro.
-- ============================================================

CREATE TABLE pagos (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                     uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                     pedido_id BIGINT NOT NULL,

                     metodo_pago_id BIGINT NOT NULL,
                     estado_pago_id BIGINT NOT NULL,

                     monto NUMERIC(14,2) NOT NULL,

                     referencia VARCHAR(150),
                     url_comprobante VARCHAR(500),

                     usuario_verificador_id BIGINT,

                     fecha_pago TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     fecha_verificacion TIMESTAMPTZ,

                     fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                     CONSTRAINT uq_pagos_uuid_publico
                       UNIQUE (uuid_publico),

                     CONSTRAINT fk_pagos_pedido
                       FOREIGN KEY (pedido_id)
                         REFERENCES pedidos(id),

                     CONSTRAINT fk_pagos_metodo
                       FOREIGN KEY (metodo_pago_id)
                         REFERENCES metodos_pago(id),

                     CONSTRAINT fk_pagos_estado
                       FOREIGN KEY (estado_pago_id)
                         REFERENCES estados_pago(id),

                     CONSTRAINT fk_pagos_usuario_verificador
                       FOREIGN KEY (usuario_verificador_id)
                         REFERENCES usuarios(id),

                     CONSTRAINT ck_pagos_monto
                       CHECK (monto > 0),

                     CONSTRAINT ck_pagos_fecha_verificacion
                       CHECK (
                         fecha_verificacion IS NULL
                           OR fecha_verificacion >= fecha_pago
                         )
);


-- ============================================================
-- 4. INDICES
-- ============================================================

CREATE INDEX idx_pagos_pedido
  ON pagos(pedido_id);

CREATE INDEX idx_pagos_metodo
  ON pagos(metodo_pago_id);

CREATE INDEX idx_pagos_estado
  ON pagos(estado_pago_id);

CREATE INDEX idx_pagos_usuario_verificador
  ON pagos(usuario_verificador_id);

CREATE INDEX idx_pagos_fecha_pago
  ON pagos(fecha_pago);

CREATE INDEX idx_pagos_referencia
  ON pagos(referencia);


-- ============================================================
-- 5. METODOS DE PAGO INICIALES
-- ============================================================

INSERT INTO metodos_pago
(nombre, descripcion)
VALUES
  (
    'EFECTIVO',
    'Pago realizado en efectivo'
  ),
  (
    'TRANSFERENCIA',
    'Pago realizado mediante transferencia bancaria o billetera digital'
  );


-- ============================================================
-- 6. ESTADOS DE PAGO INICIALES
-- ============================================================

INSERT INTO estados_pago
(nombre, descripcion)
VALUES
  (
    'PENDIENTE',
    'Pago registrado y pendiente de verificación'
  ),
  (
    'CONFIRMADO',
    'Pago verificado y aceptado'
  ),
  (
    'RECHAZADO',
    'Pago rechazado durante la verificación'
  ),
  (
    'ANULADO',
    'Pago previamente registrado que fue anulado'
  );
