-- ============================================================
-- SMART STORE
-- V1 - NUCLEO MULTIEMPRESA Y SEGURIDAD
-- ============================================================


-- PAISES

CREATE TABLE paises (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                      nombre VARCHAR(100) NOT NULL,
                      codigo_iso VARCHAR(3) NOT NULL,

                      activo BOOLEAN NOT NULL DEFAULT TRUE,

                      fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                      CONSTRAINT uq_paises_nombre
                        UNIQUE (nombre),

                      CONSTRAINT uq_paises_codigo_iso
                        UNIQUE (codigo_iso)
);


--CIUDADES

CREATE TABLE ciudades (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        pais_id BIGINT NOT NULL,
                        nombre VARCHAR(100) NOT NULL,

                        activo BOOLEAN NOT NULL DEFAULT TRUE,

                        fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT fk_ciudades_pais
                          FOREIGN KEY (pais_id)
                            REFERENCES paises(id),

                        CONSTRAINT uq_ciudades_pais_nombre
                          UNIQUE (pais_id, nombre)
);

CREATE INDEX idx_ciudades_pais_id
  ON ciudades(pais_id);


-- COMERCIOS

CREATE TABLE comercios (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                         nombre VARCHAR(150) NOT NULL,
                         nit VARCHAR(30),
                         telefono VARCHAR(20),
                         correo VARCHAR(150),
                         url_logo VARCHAR(500),

                         activo BOOLEAN NOT NULL DEFAULT TRUE,

                         fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT uq_comercios_uuid_publico
                           UNIQUE (uuid_publico),

                         CONSTRAINT uq_comercios_nit
                           UNIQUE (nit)
);


-- SEDES

CREATE TABLE sedes (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                     comercio_id BIGINT NOT NULL,
                     ciudad_id BIGINT NOT NULL,

                     nombre VARCHAR(150) NOT NULL,
                     direccion VARCHAR(200) NOT NULL,
                     telefono VARCHAR(20),

                     activo BOOLEAN NOT NULL DEFAULT TRUE,

                     fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                     CONSTRAINT uq_sedes_uuid_publico
                       UNIQUE (uuid_publico),

                     CONSTRAINT uq_sedes_comercio_nombre
                       UNIQUE (comercio_id, nombre),

                     CONSTRAINT fk_sedes_comercio
                       FOREIGN KEY (comercio_id)
                         REFERENCES comercios(id),

                     CONSTRAINT fk_sedes_ciudad
                       FOREIGN KEY (ciudad_id)
                         REFERENCES ciudades(id)
);

CREATE INDEX idx_sedes_comercio_id
  ON sedes(comercio_id);

CREATE INDEX idx_sedes_ciudad_id
  ON sedes(ciudad_id);


-- USUAEARIOS

CREATE TABLE usuarios (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                        nombres VARCHAR(100) NOT NULL,
                        apellidos VARCHAR(100) NOT NULL,
                        correo VARCHAR(150) NOT NULL,
                        telefono VARCHAR(20),
                        contrasena_hash VARCHAR(255) NOT NULL,

                        activo BOOLEAN NOT NULL DEFAULT TRUE,

                        fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT uq_usuarios_uuid_publico
                          UNIQUE (uuid_publico),

                        CONSTRAINT uq_usuarios_correo
                          UNIQUE (correo)
);


-- ROLES USUARIOS

CREATE TABLE roles (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                     nombre VARCHAR(50) NOT NULL,
                     descripcion VARCHAR(255),

                     activo BOOLEAN NOT NULL DEFAULT TRUE,

                     fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                     CONSTRAINT uq_roles_nombre
                       UNIQUE (nombre)
);


--- USUARIOS POR SEDE

CREATE TABLE usuarios_sedes (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              usuario_id BIGINT NOT NULL,
                              sede_id BIGINT NOT NULL,
                              rol_id BIGINT NOT NULL,

                              activo BOOLEAN NOT NULL DEFAULT TRUE,

                              fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT fk_usuarios_sedes_usuario
                                FOREIGN KEY (usuario_id)
                                  REFERENCES usuarios(id),

                              CONSTRAINT fk_usuarios_sedes_sede
                                FOREIGN KEY (sede_id)
                                  REFERENCES sedes(id),

                              CONSTRAINT fk_usuarios_sedes_rol
                                FOREIGN KEY (rol_id)
                                  REFERENCES roles(id),

                              CONSTRAINT uq_usuarios_sedes_usuario_sede
                                UNIQUE (usuario_id, sede_id)
);

CREATE INDEX idx_usuarios_sedes_usuario_id
  ON usuarios_sedes(usuario_id);

CREATE INDEX idx_usuarios_sedes_sede_id
  ON usuarios_sedes(sede_id);

CREATE INDEX idx_usuarios_sedes_rol_id
  ON usuarios_sedes(rol_id);


--DATOS INICIALES

INSERT INTO roles (nombre, descripcion)
VALUES
  ('OWNER', 'Propietario del negocio'),
  ('ADMIN', 'Administrador de la sede'),
  ('EMPLOYEE', 'Empleado de la sede');


INSERT INTO paises (nombre, codigo_iso)
VALUES
  ('Colombia', 'COL');
