-- ============================================================
-- SMART STORE
-- V2 - CATALOGO DE PRODUCTOS
-- ============================================================


-- ============================================================
-- 1. UNIDADES DE MEDIDA
-- ============================================================

CREATE TABLE unidades_medida (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               nombre VARCHAR(50) NOT NULL,
                               abreviatura VARCHAR(10) NOT NULL,

                               activo BOOLEAN NOT NULL DEFAULT TRUE,

                               fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT uq_unidades_medida_nombre
                                 UNIQUE (nombre),

                               CONSTRAINT uq_unidades_medida_abreviatura
                                 UNIQUE (abreviatura)
);


-- ============================================================
-- 2. CATEGORIAS
-- ============================================================

CREATE TABLE categorias (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                          comercio_id BIGINT NOT NULL,
                          nombre VARCHAR(100) NOT NULL,
                          descripcion VARCHAR(255),

                          activo BOOLEAN NOT NULL DEFAULT TRUE,

                          fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT uq_categorias_uuid_publico
                            UNIQUE (uuid_publico),

                          CONSTRAINT uq_categorias_comercio_nombre
                            UNIQUE (comercio_id, nombre),

                          CONSTRAINT fk_categorias_comercio
                            FOREIGN KEY (comercio_id)
                              REFERENCES comercios(id)
);

CREATE INDEX idx_categorias_comercio_id
  ON categorias(comercio_id);


-- ============================================================
-- 3. PRODUCTOS
-- ============================================================

CREATE TABLE productos (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                         categoria_id BIGINT NOT NULL,

                         nombre VARCHAR(150) NOT NULL,
                         descripcion TEXT,
                         marca VARCHAR(100),
                         url_imagen VARCHAR(500),

                         activo BOOLEAN NOT NULL DEFAULT TRUE,

                         fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT uq_productos_uuid_publico
                           UNIQUE (uuid_publico),

                         CONSTRAINT uq_productos_categoria_nombre
                           UNIQUE (categoria_id, nombre),

                         CONSTRAINT fk_productos_categoria
                           FOREIGN KEY (categoria_id)
                             REFERENCES categorias(id)
);

CREATE INDEX idx_productos_categoria_id
  ON productos(categoria_id);


-- ============================================================
-- 4. ATRIBUTOS
-- ============================================================

CREATE TABLE atributos (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         comercio_id BIGINT NOT NULL,

                         nombre VARCHAR(100) NOT NULL,

                         activo BOOLEAN NOT NULL DEFAULT TRUE,

                         fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT uq_atributos_comercio_nombre
                           UNIQUE (comercio_id, nombre),

                         CONSTRAINT fk_atributos_comercio
                           FOREIGN KEY (comercio_id)
                             REFERENCES comercios(id)
);

CREATE INDEX idx_atributos_comercio_id
  ON atributos(comercio_id);


-- ============================================================
-- 5. VALORES DE ATRIBUTO
-- ============================================================

CREATE TABLE valores_atributo (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                atributo_id BIGINT NOT NULL,

                                valor VARCHAR(100) NOT NULL,

                                activo BOOLEAN NOT NULL DEFAULT TRUE,

                                fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT uq_valores_atributo_atributo_valor
                                  UNIQUE (atributo_id, valor),

                                CONSTRAINT fk_valores_atributo_atributo
                                  FOREIGN KEY (atributo_id)
                                    REFERENCES atributos(id)
);

CREATE INDEX idx_valores_atributo_atributo_id
  ON valores_atributo(atributo_id);


-- ============================================================
-- 6. VARIANTES DE PRODUCTO
-- ============================================================

CREATE TABLE variantes_producto (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                                  producto_id BIGINT NOT NULL,
                                  unidad_medida_id BIGINT NOT NULL,

                                  nombre VARCHAR(150) NOT NULL,
                                  codigo_barras VARCHAR(100),

                                  activo BOOLEAN NOT NULL DEFAULT TRUE,

                                  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                  CONSTRAINT uq_variantes_producto_uuid_publico
                                    UNIQUE (uuid_publico),

                                  CONSTRAINT uq_variantes_producto_producto_nombre
                                    UNIQUE (producto_id, nombre),

                                  CONSTRAINT fk_variantes_producto_producto
                                    FOREIGN KEY (producto_id)
                                      REFERENCES productos(id),

                                  CONSTRAINT fk_variantes_producto_unidad_medida
                                    FOREIGN KEY (unidad_medida_id)
                                      REFERENCES unidades_medida(id)
);

CREATE INDEX idx_variantes_producto_producto_id
  ON variantes_producto(producto_id);

CREATE INDEX idx_variantes_producto_unidad_medida_id
  ON variantes_producto(unidad_medida_id);

CREATE INDEX idx_variantes_producto_codigo_barras
  ON variantes_producto(codigo_barras);


-- ============================================================
-- 7. ATRIBUTOS DE LAS VARIANTES
-- ============================================================

CREATE TABLE variantes_valores_atributo (
                                          variante_producto_id BIGINT NOT NULL,
                                          valor_atributo_id BIGINT NOT NULL,

                                          CONSTRAINT pk_variantes_valores_atributo
                                            PRIMARY KEY (variante_producto_id, valor_atributo_id),

                                          CONSTRAINT fk_variantes_valores_variante
                                            FOREIGN KEY (variante_producto_id)
                                              REFERENCES variantes_producto(id),

                                          CONSTRAINT fk_variantes_valores_valor
                                            FOREIGN KEY (valor_atributo_id)
                                              REFERENCES valores_atributo(id)
);

CREATE INDEX idx_variantes_valores_valor_atributo_id
  ON variantes_valores_atributo(valor_atributo_id);


-- ============================================================
-- 8. VARIANTES DISPONIBLES POR SEDE
-- ============================================================

CREATE TABLE variantes_producto_sede (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                                       sede_id BIGINT NOT NULL,
                                       variante_producto_id BIGINT NOT NULL,

                                       sku VARCHAR(100) NOT NULL,

                                       precio_costo NUMERIC(14,2),
                                       precio_venta NUMERIC(14,2) NOT NULL,

                                       activo BOOLEAN NOT NULL DEFAULT TRUE,

                                       fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                       CONSTRAINT uq_variantes_producto_sede_uuid
                                         UNIQUE (uuid_publico),

                                       CONSTRAINT uq_variantes_producto_sede_variante
                                         UNIQUE (sede_id, variante_producto_id),

                                       CONSTRAINT uq_variantes_producto_sede_sku
                                         UNIQUE (sede_id, sku),

                                       CONSTRAINT ck_variantes_producto_sede_precio_costo
                                         CHECK (precio_costo IS NULL OR precio_costo >= 0),

                                       CONSTRAINT ck_variantes_producto_sede_precio_venta
                                         CHECK (precio_venta >= 0),

                                       CONSTRAINT fk_variantes_producto_sede_sede
                                         FOREIGN KEY (sede_id)
                                           REFERENCES sedes(id),

                                       CONSTRAINT fk_variantes_producto_sede_variante
                                         FOREIGN KEY (variante_producto_id)
                                           REFERENCES variantes_producto(id)
);

CREATE INDEX idx_variantes_producto_sede_sede_id
  ON variantes_producto_sede(sede_id);

CREATE INDEX idx_variantes_producto_sede_variante_id
  ON variantes_producto_sede(variante_producto_id);


-- ============================================================
-- DATOS INICIALES
-- ============================================================

INSERT INTO unidades_medida (nombre, abreviatura)
VALUES
  ('Unidad', 'und'),
  ('Kilogramo', 'kg'),
  ('Gramo', 'g'),
  ('Litro', 'L'),
  ('Mililitro', 'ml');
