-- ============================================================
-- V3 - INVENTARIO Y MOVIMIENTOS DE INVENTARIO
-- Smart Store
-- ============================================================


-- ============================================================
-- 1. TIPOS DE MOVIMIENTO DE INVENTARIO
-- ============================================================

CREATE TABLE tipos_movimiento_inventario (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                           nombre VARCHAR(50) NOT NULL,
                                           descripcion VARCHAR(255),

                                           activo BOOLEAN NOT NULL DEFAULT TRUE,

                                           fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                           CONSTRAINT uq_tipos_movimiento_inventario_nombre
                                             UNIQUE (nombre)
);


-- ============================================================
-- 2. INVENTARIOS
-- Estado actual del inventario de una variante en una sede.
--
-- La sede NO se almacena aquí porque ya puede obtenerse desde
-- variantes_producto_sede.
--
-- cantidad_disponible NO se almacena:
--
-- cantidad_disponible =
--     cantidad_existencia - cantidad_reservada
-- ============================================================

CREATE TABLE inventarios (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           variante_producto_sede_id BIGINT NOT NULL,

                           cantidad_existencia NUMERIC(14,3) NOT NULL DEFAULT 0,
                           cantidad_reservada NUMERIC(14,3) NOT NULL DEFAULT 0,

                           fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_inventarios_variante_producto_sede
                             FOREIGN KEY (variante_producto_sede_id)
                               REFERENCES variantes_producto_sede(id),

                           CONSTRAINT uq_inventarios_variante_producto_sede
                             UNIQUE (variante_producto_sede_id),

                           CONSTRAINT ck_inventarios_cantidad_existencia
                             CHECK (cantidad_existencia >= 0),

                           CONSTRAINT ck_inventarios_cantidad_reservada
                             CHECK (cantidad_reservada >= 0),

                           CONSTRAINT ck_inventarios_reservada_no_supera_existencia
                             CHECK (cantidad_reservada <= cantidad_existencia)
);


-- ============================================================
-- 3. MOVIMIENTOS DE INVENTARIO
--
-- Cada movimiento registra cómo cambió:
--
-- 1. La existencia física.
-- 2. La cantidad reservada.
--
-- Los movimientos representan historial y no deben modificarse
-- después de ser registrados.
-- ============================================================

CREATE TABLE movimientos_inventario (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                      inventario_id BIGINT NOT NULL,
                                      tipo_movimiento_inventario_id BIGINT NOT NULL,

                                      cantidad_existencia NUMERIC(14,3) NOT NULL DEFAULT 0,
                                      cantidad_reservada NUMERIC(14,3) NOT NULL DEFAULT 0,

                                      usuario_id BIGINT,

                                      observacion VARCHAR(500),

                                      fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                      CONSTRAINT fk_movimientos_inventario_inventario
                                        FOREIGN KEY (inventario_id)
                                          REFERENCES inventarios(id),

                                      CONSTRAINT fk_movimientos_inventario_tipo
                                        FOREIGN KEY (tipo_movimiento_inventario_id)
                                          REFERENCES tipos_movimiento_inventario(id),

                                      CONSTRAINT fk_movimientos_inventario_usuario
                                        FOREIGN KEY (usuario_id)
                                          REFERENCES usuarios(id),

                                      CONSTRAINT ck_movimientos_inventario_cantidad
                                        CHECK (
                                          cantidad_existencia <> 0
                                            OR cantidad_reservada <> 0
                                          )
);


-- ============================================================
-- 4. ÍNDICES
-- ============================================================

CREATE INDEX idx_movimientos_inventario_inventario
  ON movimientos_inventario(inventario_id);

CREATE INDEX idx_movimientos_inventario_tipo
  ON movimientos_inventario(tipo_movimiento_inventario_id);

CREATE INDEX idx_movimientos_inventario_usuario
  ON movimientos_inventario(usuario_id);

CREATE INDEX idx_movimientos_inventario_fecha
  ON movimientos_inventario(fecha_creacion);


-- ============================================================
-- 5. TIPOS DE MOVIMIENTO INICIALES
-- ============================================================

INSERT INTO tipos_movimiento_inventario
(nombre, descripcion)
VALUES
  (
    'COMPRA',
    'Ingreso de existencias por recepción de una compra'
  ),
  (
    'RESERVA',
    'Reserva de existencias asociada a un pedido'
  ),
  (
    'LIBERACION',
    'Liberación de existencias previamente reservadas'
  ),
  (
    'ENTREGA',
    'Salida física de existencias por entrega de un pedido'
  ),
  (
    'AJUSTE_ENTRADA',
    'Ajuste manual que incrementa la existencia'
  ),
  (
    'AJUSTE_SALIDA',
    'Ajuste manual que disminuye la existencia'
  );
