-- ============================================================
-- V6 - CLIENTES Y DIRECCIONES
-- Smart Store
-- ============================================================


-- ============================================================
-- 1. CLIENTES
--
-- El cliente pertenece al comercio, NO a una sede.
--
-- Esto permite que el mismo cliente pueda comprar en distintas
-- sedes del mismo comercio sin duplicar su información.
--
-- El teléfono será especialmente importante para identificar
-- clientes provenientes de WhatsApp.
-- ============================================================

CREATE TABLE clientes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                        comercio_id BIGINT NOT NULL,

                        nombres VARCHAR(100) NOT NULL,
                        apellidos VARCHAR(100),

                        telefono VARCHAR(20) NOT NULL,
                        correo VARCHAR(150),

                        activo BOOLEAN NOT NULL DEFAULT TRUE,

                        fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT uq_clientes_uuid_publico
                          UNIQUE (uuid_publico),

                        CONSTRAINT fk_clientes_comercio
                          FOREIGN KEY (comercio_id)
                            REFERENCES comercios(id),

                        CONSTRAINT uq_clientes_comercio_telefono
                          UNIQUE (comercio_id, telefono),

                        CONSTRAINT ck_clientes_nombres_no_vacio
                          CHECK (btrim(nombres) <> ''),

                        CONSTRAINT ck_clientes_telefono_no_vacio
                          CHECK (btrim(telefono) <> '')
);


-- ============================================================
-- 2. DIRECCIONES DE CLIENTES
--
-- Un cliente puede tener múltiples direcciones.
--
-- Ejemplos:
-- - Casa
-- - Trabajo
-- - Casa de un familiar
--
-- Una sola dirección puede estar marcada como predeterminada.
-- ============================================================

CREATE TABLE direcciones_cliente (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                                   cliente_id BIGINT NOT NULL,
                                   ciudad_id BIGINT NOT NULL,

                                   nombre VARCHAR(100),

                                   direccion VARCHAR(255) NOT NULL,

                                   barrio VARCHAR(100),

                                   referencia VARCHAR(255),

                                   es_predeterminada BOOLEAN NOT NULL DEFAULT FALSE,

                                   activo BOOLEAN NOT NULL DEFAULT TRUE,

                                   fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT uq_direcciones_cliente_uuid_publico
                                     UNIQUE (uuid_publico),

                                   CONSTRAINT fk_direcciones_cliente_cliente
                                     FOREIGN KEY (cliente_id)
                                       REFERENCES clientes(id),

                                   CONSTRAINT fk_direcciones_cliente_ciudad
                                     FOREIGN KEY (ciudad_id)
                                       REFERENCES ciudades(id),

                                   CONSTRAINT ck_direcciones_cliente_direccion_no_vacia
                                     CHECK (btrim(direccion) <> '')
);


-- ============================================================
-- 3. ÍNDICES
-- ============================================================

CREATE INDEX idx_clientes_comercio
  ON clientes(comercio_id);

CREATE INDEX idx_clientes_telefono
  ON clientes(telefono);

CREATE INDEX idx_direcciones_cliente_cliente
  ON direcciones_cliente(cliente_id);

CREATE INDEX idx_direcciones_cliente_ciudad
  ON direcciones_cliente(ciudad_id);


-- ============================================================
-- 4. UNA SOLA DIRECCIÓN PREDETERMINADA POR CLIENTE
--
-- PostgreSQL permite índices únicos parciales.
--
-- Este índice solo considera las filas donde
-- es_predeterminada = TRUE.
--
-- Por lo tanto:
--
-- Casa     -> TRUE
-- Trabajo  -> FALSE
-- Otra     -> FALSE
--
-- es válido.
--
-- Pero:
--
-- Casa     -> TRUE
-- Trabajo  -> TRUE
--
-- será rechazado por PostgreSQL.
-- ============================================================

CREATE UNIQUE INDEX uq_direcciones_cliente_predeterminada
  ON direcciones_cliente(cliente_id)
  WHERE es_predeterminada = TRUE;
