-- ============================================================
-- V7 - COMPRAS
-- Smart Store
-- ============================================================


-- ============================================================
-- 1. ESTADOS DE COMPRA
-- ============================================================

CREATE TABLE estados_compra (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              nombre VARCHAR(50) NOT NULL,
                              descripcion VARCHAR(255),

                              activo BOOLEAN NOT NULL DEFAULT TRUE,

                              fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT uq_estados_compra_nombre
                                UNIQUE (nombre)
);


-- ============================================================
-- 2. COMPRAS
--
-- Una compra pertenece a una sede porque la mercancía
-- recibida incrementará el inventario de esa sede.
--
-- usuario_id identifica quién registró la operación.
-- ============================================================

CREATE TABLE compras (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       uuid_publico UUID NOT NULL DEFAULT gen_random_uuid(),

                       sede_id BIGINT NOT NULL,
                       estado_compra_id BIGINT NOT NULL,
                       usuario_id BIGINT,

                       observacion VARCHAR(500),

                       fecha_compra TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       fecha_recepcion TIMESTAMPTZ,

                       fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uq_compras_uuid_publico
                         UNIQUE (uuid_publico),

                       CONSTRAINT fk_compras_sede
                         FOREIGN KEY (sede_id)
                           REFERENCES sedes(id),

                       CONSTRAINT fk_compras_estado
                         FOREIGN KEY (estado_compra_id)
                           REFERENCES estados_compra(id),

                       CONSTRAINT fk_compras_usuario
                         FOREIGN KEY (usuario_id)
                           REFERENCES usuarios(id),

                       CONSTRAINT ck_compras_fechas
                         CHECK (
                           fecha_recepcion IS NULL
                             OR fecha_recepcion >= fecha_compra
                           )
);


-- ============================================================
-- 3. DETALLE DE COMPRA
--
-- Cada fila representa una variante comprada para la sede.
--
-- Ejemplo:
--
-- Compra #20
-- Coca-Cola 400 ml | 24 unidades | $2.000 c/u
--
-- No almacenamos total:
-- total = cantidad * costo_unitario
-- ============================================================

CREATE TABLE detalles_compra (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               compra_id BIGINT NOT NULL,
                               variante_producto_sede_id BIGINT NOT NULL,

                               cantidad NUMERIC(14,3) NOT NULL,
                               costo_unitario NUMERIC(14,2) NOT NULL,

                               fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_detalles_compra_compra
                                 FOREIGN KEY (compra_id)
                                   REFERENCES compras(id),

                               CONSTRAINT fk_detalles_compra_variante_producto_sede
                                 FOREIGN KEY (variante_producto_sede_id)
                                   REFERENCES variantes_producto_sede(id),

                               CONSTRAINT ck_detalles_compra_cantidad
                                 CHECK (cantidad > 0),

                               CONSTRAINT ck_detalles_compra_costo_unitario
                                 CHECK (costo_unitario >= 0),

                               CONSTRAINT uq_detalles_compra_variante
                                 UNIQUE (compra_id, variante_producto_sede_id)
);


-- ============================================================
-- 4. RELACIÓN ENTRE DETALLE DE COMPRA Y MOVIMIENTO
--
-- Esta tabla permite conocer exactamente qué movimiento de
-- inventario fue generado por qué detalle de compra.
--
-- Evitamos columnas genéricas como:
--
-- tipo_referencia
-- referencia_id
--
-- porque no podrían protegerse correctamente mediante FK.
-- ============================================================

CREATE TABLE movimientos_inventario_compra (
                                             movimiento_inventario_id BIGINT NOT NULL,
                                             detalle_compra_id BIGINT NOT NULL,

                                             CONSTRAINT pk_movimientos_inventario_compra
                                               PRIMARY KEY (
                                                            movimiento_inventario_id,
                                                            detalle_compra_id
                                                 ),

                                             CONSTRAINT fk_movimientos_inventario_compra_movimiento
                                               FOREIGN KEY (movimiento_inventario_id)
                                                 REFERENCES movimientos_inventario(id),

                                             CONSTRAINT fk_movimientos_inventario_compra_detalle
                                               FOREIGN KEY (detalle_compra_id)
                                                 REFERENCES detalles_compra(id)
);


-- ============================================================
-- 5. ÍNDICES
-- ============================================================

CREATE INDEX idx_compras_sede
  ON compras(sede_id);

CREATE INDEX idx_compras_estado
  ON compras(estado_compra_id);

CREATE INDEX idx_compras_usuario
  ON compras(usuario_id);

CREATE INDEX idx_compras_fecha_compra
  ON compras(fecha_compra);

CREATE INDEX idx_detalles_compra_compra
  ON detalles_compra(compra_id);

CREATE INDEX idx_detalles_compra_variante_producto_sede
  ON detalles_compra(variante_producto_sede_id);

CREATE INDEX idx_movimientos_inventario_compra_detalle
  ON movimientos_inventario_compra(detalle_compra_id);


-- ============================================================
-- 6. ESTADOS INICIALES
-- ============================================================

INSERT INTO estados_compra
(nombre, descripcion)
VALUES
  (
    'REGISTRADA',
    'Compra registrada pero cuya mercancía aún no ha sido recibida'
  ),
  (
    'RECIBIDA',
    'Mercancía recibida e incorporada al inventario'
  ),
  (
    'CANCELADA',
    'Compra cancelada y que no debe afectar el inventario'
  );
